version: '3.8'

services:
  node-app:
    container_name: my-node-container
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production  # Set environment variable
    volumes:
      - .:/app  # Mount current directory for live changes (optional)
      - /app/node_modules  # Prevent overwriting node_modules

